config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :price_per_night, presence: true
  validates :number_of_guests, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  def index
    @flats = Flat.all
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to @flat
    else
      render :new
    end
  end

  def edit
  end

  def update
    @flat.update(flat_params)
    redirect_to @flat
  end

  def destroy
    @flat.destroy
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<h1>Edit <%= @flat.name %></h1>

<div class="container">
<%= simple_form_for @flat do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit "Edit the flat", class: "btn btn-primary" %>
  <%= f.button :button, 'Cancel', type: :reset, class: 'btn btn-danger' %>
<% end %>
</div>

app/views/flats/index.html.erb
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand"><h1>Rails Simple AirBnB</h1></a>
  <form class="form-inline">
    <input class="form-control" type="search" placeholder="Search.." aria-label="Search">
    <button class="btn btn-success" type="submit">Search</button>
    <%= link_to 'Create new flats', new_flat_path, class: "btn btn-primary" %>
  </form>
</nav>

<div class="card-container">
      <% @flats.each do |flat| %>
        <div class="card-flat">
          <img src="https://source.unsplash.com/1600x900/?flat,house&rand=<%= rand( 9999) %>" />
          <div class="card-flat-info">
            <div>
              <%= link_to flat_path(flat) do %>
                  <h2><%= flat.name %></h2>
                  <p><%= flat.description %></p>
                <% end %>
            </div>
            <p><i class="fas fa-dollar-sign"></i> <%= flat.price_per_night %></p>
            <p><i class="fas fa-user-friends"></i> <%= flat.number_of_guests %></p>
          </div>
        </div>
      <% end %>
</div>

app/views/flats/new.html.erb
<h1>Add a Flat</h1>

<div class="container">
<%= simple_form_for @flat do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit "Add flat", class: "btn btn-primary" %>
  <%= f.button :button, 'Cancel', type: :reset, class: 'btn btn-danger' %>
<% end %>
</div>

app/views/flats/show.html.erb
<div class="card-container">
  <div class="card" style="width: 100%;">

    <div class="card-body">
    <img src="https://source.unsplash.com/1600x900/?flat,house" class="card-img-top" alt="...">
    <h3 class="card-title"><%= @flat.name %></h3>
    <h4 class="card-subtitle"><small><%= @flat.description %></small></h4>
    <p class="card-text"><%= @flat.address %></p>

        <hr>

        <%= link_to 'Edit your flat', edit_flat_path, class: "card-link" %>
        <%= link_to "Back to the list", flats_path, class: "card-link"%>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
   <!-- ... -->
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>